# Generated by Django 4.0.3 on 2022-05-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-important']},
        ),
    ]
