# Generated by Django 4.0.3 on 2022-05-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tasklist_task_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
